apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuseapp.fullname" . }}
  labels:
    {{- include "fuseapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
    - name: 9779-tcp
      protocol: TCP
      port: 9779
      targetPort: 9779
  selector:
    {{- include "fuseapp.selectorLabels" . | nindent 4 }}
